BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Players" (
	"PlayerId"	INTEGER NOT NULL UNIQUE,
	"Username"	TEXT NOT NULL UNIQUE,
	"Password"	TEXT NOT NULL,
	"Balance"	INTEGER NOT NULL,
	PRIMARY KEY("PlayerId" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Tetris" (
	"RegisterId"	INTEGER NOT NULL,
	"PlayerId"	INTEGER NOT NULL,
	"Score"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("RegisterId" AUTOINCREMENT),
	FOREIGN KEY("PlayerId") REFERENCES "Players"("PlayerId")
);
COMMIT;
